[build]
  command = "./build.sh" # Commande de construction pour votre projet
  publish = "./Frontend" # Dossier de construction pour votre projet React

[build.environment]
  API_URL = "./Backend/src" # URL de votre API Nest
