[build]
  command = "./build.sh" # Commande de construction pour votre projet
  publish = "./Frontend/build" # Dossier de construction pour votre projet React

[build.environment]
  API_URL = "/.netlify/Backend/src" # URL de votre API Nest
